name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Create mock firebase_options.dart for CI
        run: |
          mkdir -p lib
          if [ ! -f "lib/firebase_options.dart" ]; then
            echo "import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;" > lib/firebase_options.dart
            echo "class DefaultFirebaseOptions { static FirebaseOptions get currentPlatform => android; static const FirebaseOptions android = FirebaseOptions(apiKey: 'DUMMY', appId: 'DUMMY', messagingSenderId: 'DUMMY', projectId: 'DUMMY', storageBucket: 'DUMMY'); }" >> lib/firebase_options.dart
          fi

      - name: Generate code
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test
